{% set version = "1.6.2" %}
{% set sha256 = "8731e08a0c4e389d8695a40072ada4512641c113b6cace8f4cfbe8eb7e9aedeb" %}

package:
  name: autograd
  version: {{ version }}

source:
  fn: autograd-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/a/autograd/autograd-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
    - numpy >=1.10
    - future >=0.15.2
    - scipy >=0.17

  run:
    - python >=3.6
    - numpy >=1.10
    - future >=0.15.2
    - scipy >=0.17

test:
  imports:
    - autograd
    - autograd.numpy
    - autograd.scipy
    - autograd.scipy.stats

about:
  home: https://github.com/HIPS/autograd
  license: MIT
  license_file: license.txt
  summary: Efficiently computes derivatives of numpy code.

extra:
  recipe-maintainers:
    - richardotis
    - ericmjl
    - benvial
